# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: 'Kitchen (macOS)'
'on': ['push', 'pull_request']

env:
  KITCHEN_LOCAL_YAML: 'kitchen.macos.yml'

jobs:
  test-13:
    runs-on: 'macos-13'
    strategy:
      fail-fast: false
      matrix:
        instance:
          - default-macos-13-latest
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v4'
      - name: 'Set up Bundler cache'
        uses: 'actions/cache@v4'
        with:
          path: 'vendor/bundle'
          key: "${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}"
          restore-keys: "${{ runner.os }}-gems-"
      - name: 'Run Bundler'
        run: |
          ruby --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: 'Run Test Kitchen'
        run: 'bundle exec kitchen verify ${{ matrix.instance }}'
