# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: 'Kitchen (Windows)'
'on': ['workflow_dispatch']

env:
  machine_user: kitchen
  machine_pass: Pass@word1
  machine_port: 5985
  KITCHEN_LOCAL_YAML: 'kitchen.windows.yml'

jobs:
  test-2022:
    runs-on: 'windows-2022'
    strategy:
      fail-fast: false
      matrix:
        instance:
          - default-windows-2022-latest
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v4'
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.6'
          bundler-cache: true
      - name: 'Set up test user'
        run: |
          $password = ConvertTo-SecureString $env:machine_pass -AsPlainText -Force
          New-LocalUser $env:machine_user -Password $password
          Add-LocalGroupMember -Group "Administrators" -Member $env:machine_user
      - name: 'Set up WinRM'
        run: |
          Set-WSManQuickConfig -Force
      - name: 'Run Bundler'
        run: |
          ruby --version
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: 'Run Test Kitchen'
        run: 'bundle exec kitchen verify ${{ matrix.instance }}'
  test-2019:
    runs-on: 'windows-2019'
    strategy:
      fail-fast: false
      matrix:
        instance:
          - default-windows-2019-latest
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v4'
      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.6'
          bundler-cache: true
      - name: 'Set up test user'
        run: |
          $password = ConvertTo-SecureString $env:machine_pass -AsPlainText -Force
          New-LocalUser $env:machine_user -Password $password
          Add-LocalGroupMember -Group "Administrators" -Member $env:machine_user
      - name: 'Set up WinRM'
        run: |
          Set-WSManQuickConfig -Force
      - name: 'Run Test Kitchen'
        run: 'bundle exec kitchen verify ${{ matrix.instance }}'
